### PR TITLE
Auto config

### PR DESCRIPTION
**Pull request by andreyorst**
**plug.kak** now automatically loads plugins after installation.
Externalized configuration process to separate command, which enables automatic configuration of plugin right after installation. No need to reload Kakoune after installation of a plugin.

Also updated some regexps for syntax highlighting.

### CODE REVIEW

**Comment by Delapouite** [comment]
Skimming through the code, I see that you use a custom delimiter to store values in option and split the string with `IFS='┆'` afterwards. Is there any reason why you don't use the built-in `str-list` option type to avoid this trick?

**Comment by andreyorst** [comment]
I don't see the way how built-in `str-list` will help me in `for` loops inside of shell expansions, because it's the only place where I use those lists.

**Comment by andreyorst** [comment]
because `str-list` stores items with a space as delimiter, which is unacceptable in my case, since items can have spaces, and lot of other characters too. `┆` seems like quite rare separator, and I suppose it will never actually be used in configuration of any plugin. Well except of some `indent-guides.kak` plugin, but there's none at the moment.

I have plenty of other weird separators: `|▏¦┆│⎸╱ ╲`

**Comment by Delapouite** [comment]
You're right. My question is just rhetorical and in practice it often feels easier to use your technic instead of relying on the new pattern introduced with in the september version of kakoune:

```sh
eval "set -- $kak_opt_str_list"
while [ "$1" ]; do
    shift
done
```
I don't like this `$1` variable very much.

**Comment by andreyorst** [comment]
this not gonna work anyway. It will still iterate over spaces, and my array can coutain spaces inside items. That's why I don't like POSIX. It doesn't have true arrays within the standard, and the only reliable way is to use weird separators

**Comment by andreyorst** [comment]
> It will still iterate over spaces, and my array can contain spaces inside items. 

Or not. I've actually tried it. Seems that Kakoune does something with `$kak_opt_str_list` when it sees it with `set -- ` in same scope. Am I right?

**Comment by andreyorst** [comment]
for some reason this doesn't work for me in termux kakoune. I think I'll stick with current solution for now

**Pull request merged**
