### PR TITLE
Fix "ensure" link

### PR DESCRIPTION
**Pull request by maxdevjs**
Also minor text fixes.

### CODE REVIEW

**Comment by andreyorst** [comment]
Thanks for this patch! This repo is a mirror of gitlab repo though. If you don't mind I'll close this, and apply the patch there, or if you have Gitlab account you can submit PR there if you want. What do you think?

**Comment by maxdevjs** [comment]
I do not mind :)

By the way, I read in a comment somewhere that plugin repos are ~~scattered~~ hosted in various sites. Kakoune [plugins](http://kakoune.org/plugins.html) page only gather from `github`, am I correct?

**Comment by andreyorst** [comment]
Yes, that's why I keep mirrors here. I've decided to fully move to GitLab some time ago, but had to keep these repos for visibility.

**Comment by andreyorst** [comment]
I've applied your patch. Thanks!

**Comment by maxdevjs** [comment]
Thanks to you for the huge amount of contributions!
Anyway, markdown anchors seem broken on `gitlab`... :)

As I started to use `kak` a couple days ago and found your plugins, I leave a few questions here:

- do you push your changes to `gitlab` and then sync to `github`?
- is the process sync automatic or manual?
- and is it a consistent workflow? I see that last update to dotfiles on `github` has been pushed before than on `gitlab`, making me thing that the workflow it was the opposite (push to `github`, then sync to `gitlab`)

**Pull request closed without merging**
